name = "kimpure/utf16"
version = "0.1.0"
description = "luau-utf16 is a library for using utf16 in luau."
authors = ["sunwoo"]
repository = "https://github.com/kimpure/luau-utf16"
license = "MIT"

[target]
environment = "luau"
lib = "init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
